name: "Delete Terraform Infrastructure"
on:
    pull_request:
      types:
        - closed
env:      
    TF_WORKSPACE: "panduhz-backend-test"


jobs:
  delete_infra:
    name: "Delete Infrastructure"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete Infrastructure
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: |
          # Example script to delete resources using Terraform Cloud API
          export TF_WORKSPACE="panduhz-backend-test"
          export TF_ORG="panduhz"
          export TF_API_URL="https://app.terraform.io/api/v2"
          
          # Make API call to delete resources
          curl \
            --header "Authorization: Bearer $TF_API_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            --request DELETE \
            $TF_API_URL/workspaces/$TF_ORG/$TF_WORKSPACE/destroy
